// Generated by CoffeeScript 1.10.0
(function() {
  var ButtonClass;

  ButtonClass = (function() {
    function ButtonClass() {
      this.properties = {
        visibility: {
          name: 'Visible',
          value: true,
          type: 'checkbox'
        },
        name: {
          name: 'Value',
          value: 'Sample text',
          type: 'text'
        }
      };
      this.name = 'Test';
      this.cmpName = 'cmp-button';
    }

    return ButtonClass;

  })();

  window.ButtonClass = ButtonClass;

}).call(this);
