// Generated by CoffeeScript 1.10.0
(function() {
  window.ButtonOptions = {
    template: "<button class=\"btn\" style=\"width: 100%; height: 100%; overflow: hidden; pointer-events: none;\"\n  v-text=\"cmp.properties.name.value\"\n  v-show=\"cmp.properties.visibility.value\">\n  </button>",
    props: ['cmp']
  };

}).call(this);
