// Generated by CoffeeScript 1.10.0
(function() {
  window.ButtonOptions = {
    template: "<button class=\"btn\" :style=\"{width: cmp.properties.width+'%', height: cmp.properties.height+'%'}\"\n  v-text=\"cmp.properties.name.value\"\n  v-show=\"cmp.properties.visibility.value\">\n  </button>",
    props: ['cmp']
  };

}).call(this);
